### ISSUE TITLE
newtab可以自动显示多功能搜索框吗

### ISSUE THREAD

**Issue by ugirc** [gdh1995/vimium-c-helpers#7]
现在我用新标签页修改器打开newtab是全空白的，我需要按下o才能显示搜索栏，能不能自动打开？

如下图所示：
![image](https://user-images.githubusercontent.com/46078304/101969727-f501e080-3c60-11eb-88f5-bf339b052566.png)

**Comment by gdh1995** [comment]
在做了再做了（打开原神

**Comment by ugirc** [comment]
> 在做了在做了（打开原神

优秀🚀🚀🚀

**Comment by yuriteixeira** [comment]
Hi :) How is the status of this issue? Having the search bar opened as soon as I open a tab is what is missing to make this a full replacement of the default chrome behaviour (new tab leading to focused omni bar).

**Comment by gdh1995** [comment]
@ugirc  @yuriteixeira Hello Vimium C v1.90.2 has supported this feature: you may add `map t createTab $then="Vomnibar.activate"` to custom key mappings.

`$then` can be a mapped key sequence or a command name, and when it's a key sequence like `o` and `g0`, `createTab` will invoke the mapping rule when a new tab gets ready.

If you're using global (browser-level) shortcuts, then `shortcut createTab $then="o"` should also work.

**Comment by ugirc** [comment]
> @ugirc @yuriteixeira Hello Vimium C v1.90.2 has supported this feature: you may add `map t createTab $then="Vomnibar.activate"` to custom key mappings.
> 
> `$then` can be a mapped key sequence or a command name, and when it's a key sequence like `o` and `g0`, `createTab` will invoke the mapping rule when a new tab gets ready.
> 
> If you're using global (browser-level) shortcuts, then `shortcut createTab $then="o"` should also work.

请问我设置的正确吗？我现在这样还是无法自动打开搜索栏

是用`map t createTab $then="o"` 还是用 `map t createTab $then="Vomnibar.activate"`

另外当我想用ctrl+t打开新标签的时候是直接在设置里面写 `shortcut createTab $then="o"` 吗？我试了好像没有效果

我的版本：
![image](https://user-images.githubusercontent.com/46078304/123379628-fe311a00-d5c0-11eb-936f-afe893f27174.png)

**Comment by gdh1995** [comment]
呃我也没成功，我调试一下。

我之前是在微度那个页面上成功了

**Comment by gdh1995** [comment]
Update: `$then="Vomnibar.activate"` should work.

There seems a bug about `$then="o"`. I'll fix it in a next version of Vimium C.

**Comment by michielappelman** [comment]
On macOS with Firefox 89.0.2 and Vimium C version 1.90.2 this (`map t createTab $then="Vomnibar.activate"`) doesn't seem to work. It just opens a regular new tab with New Tab Adapter (set to `newtab.html`) without the Vomnibar opening, exactly how it worked without the `then` statement.

**Comment by gdh1995** [comment]
Sorry... I'll do more tests before giving any more fake news...

**Comment by gdh1995** [comment]
@michielappelman @ugirc Sorry, Vimium C v1.90.2 is not compatible with `Focus web page when creating a new tab` (aka `将键盘焦点从浏览器地址栏移动到网页本身`)...

This has been fixed in the latest code, but there're so many changes in development that a new release won't arrive in recent weeks.

**Comment by ugirc** [comment]
> @michielappelman @ugirc Sorry, Vimium C v1.90.2 is not compatible with `Focus web page when creating a new tab` (aka `将键盘焦点从浏览器地址栏移动到网页本身`)...
> 
> This has been fixed in the latest code, but there're so many changes in development that a new release won't arrive in recent weeks.

Thank you

**Comment by gdh1995** [comment]
Hello, now I find a working around in v1.90.2 to bypass `Focus web page when ...`: You may copy `location.href` of the `newtab.html` in NewTab Adapter, which will be like `moz-extension://<ext-uuid>/newtab.html#content`, and set it as Vimium C's `New Tab URL`.

Then `map t createTab $then="Vomnibar.activate"` and `shortcut createTab $then="Vomnibar.activate"` will open the html file directly with keyboard focus in page content, and Vomnibar should show on it.

This working around has two disadvantages:
* It affects `New Tab URL` and uses a private URL only existing in a local Firefox profile, so when it's synced / backup-restored, it may not work on other computers
  * an awkward tip is that settings syncing may not work yet - there's an issue reporting it in Vimium repo, but I haven't done tests
* Extension shortcuts can not override Firefox's default shortcuts, like `Ctrl+T` on Windows, and if you use a Firefox shortcut to create a new tab, then the page won't auto open Vomnibar.

Anyway, a next version, which may be named v1.92, will fix this bug.

**Comment by michielappelman** [comment]
That work-around works perfectly, thanks!

**Comment by gdh1995** [comment]
In Vimium C v1.92.4, the bugs mentioned above have been solved.

**Comment by michielappelman** [comment]
The new update seems to remove the use of the work-around (i.e. using the NewTab Adapter private URL in 'New Tab URL' in Vimium C), but changing that back to default (i.e. `about:newtab`) also doesn't work.

I have tried 

 - `map t createTab $then="Vomnibar.activate"`
 - `map t createTab $then="o"`

neither of whick works... Is there anything I'm missing?

**Comment by gdh1995** [comment]
What's your version of Vimium C?


When you said it did not work, what's your NewTab URL on Vimium C Options?



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2021年9月15日(周三) 晚上7:45
收件人: ***@***.***&gt;;
抄送: "Dahan ***@***.***&gt;;"State ***@***.***&gt;;
主题: Re: [gdh1995/vimium-c-helpers] newtab可以自动显示多功能搜索框吗 (#7)




 
The new update seems to remove the use of the work-around (i.e. using the NewTab Adapter private URL in 'New Tab URL' in Vimium C), but changing that back to default (i.e. about:newtab) also doesn't work.
 
I have tried
  
map t createTab $then="Vomnibar.activate" 

map t createTab $then="o" 
 
neither of whick works... Is there anything I'm missing?
 
—
You are receiving this because you modified the open/close state.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by michielappelman** [comment]
Version 1.92.4 for Firefox on macOS. NewTab URL is now set to the default again: `about:newtab`.

NewTab Adapter page is set to `newtab.html` and checked "Focus web page..." and "Interact with Vimium C"

**Comment by gdh1995** [comment]
Um, there's a small bug in v1.92.4, and you may write instead:
```
map t openUrl $then="o"
# or
map t openUrl $then="Vomnibar.activate"
```

A better way (although affecting settings syncing) is to set `New tab URL` on Vimium C Options `moz-extension://<UUID-of-NewTabAdapter>/newtab.html#content`

**Comment by michielappelman** [comment]
> Um, there's a small bug in v1.92.4, and you may write instead:
> 
> ```
> map t openUrl $then="o"
> # or
> map t openUrl $then="Vomnibar.activate"
> ```

Great work around! This indeed works (with `New tab URL` being set to the default `about:newtab`).

> A better way (although affecting settings syncing) is to set `New tab URL` on Vimium C Options `moz-extension://<UUID-of-NewTabAdapter>/newtab.html#content`

This doesn't seem to have any effect whatsoever. The Vomnibar is not opened either by using `map t openUrl $then="Vomnibar.activate"` or `map t createTab $then="Vomnibar.activate"`.

**Comment by gdh1995** [comment]
Okay, then the bug is a little bigger than I once thought.



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2021年9月17日(周五) 晚上7:14
收件人: ***@***.***&gt;;
抄送: "Dahan ***@***.***&gt;;"State ***@***.***&gt;;
主题: Re: [gdh1995/vimium-c-helpers] newtab可以自动显示多功能搜索框吗 (#7)




  
Um, there's a small bug in v1.92.4, and you may write instead:
 map t openUrl $then="o" # or map t openUrl $then="Vomnibar.activate"   
Great work around! This indeed works (with New tab URL being set to the default about:newtab).
  
A better way (although affecting settings syncing) is to set New tab URL on Vimium C Options moz-extension://<UUID-of-NewTabAdapter&gt;/newtab.html#content
  
This doesn't seem to have any effect whatsoever. The Vomnibar is not opened either by using map t openUrl $then="Vomnibar.activate" or map t createTab $then="Vomnibar.activate".
 
—
You are receiving this because you modified the open/close state.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by michielappelman** [comment]
Seems since v1.93.0 the following works perfectly: `map t runKey keys="createTab+Vomnibar.activate"`
